# name: Discord Notification Blog

# on:
#   push: 
#     branches:
#       - main

# jobs:
#   notify:
#     runs-on: ubuntu-latest 
    
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Send message to Discord
#         uses: appleboy/discord-action@v1.2.0
#         with:
#           webhook_url: ${{ secrets.WEBHOOK_URL }}
#           username: "Tin nháº¯n cá»§a Paimon"
#           message: |
#             ğŸš€ **CÃ³ code má»›i vá»«a Ä‘Æ°á»£c Push!**
#             - **NgÆ°á»i thá»±c hiá»‡n:** ${{ github.actor }}
#             - **Ná»™i dung commit:** ${{ github.event.head_commit.message }}
#             - **Link xem thay Ä‘á»•i:** ${{ github.event.head_commit.url }}